version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"

  app:
    image: my-java-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker